config/routes.rb
OverlookApp::Application.routes.draw do

  root to: 'welcome#index'
  get '/about' => 'welcome#about'
  # get '/thanks' => 'welcome#thanks'

  resources :entries
  resources :users
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :message
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def create
    Entry.create(message: params[:message])
    redirect_to about_path, flash: { :thanks => "Thanks for signing up"}
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      render json: @user
    else
      render flash: { :thanks => "Sorry you can't register so get out"}
    end
  end




end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
    @entries = Entry.all
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OverlookApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name, 'Name' %>
  <%= f.text_field :name %>
  <%= f.submit "Register" %>
<% end %>
<p id="welcome"></p>

app/views/welcome/about.html.erb
<% if flash[:thanks] %>
  <p>Thanks for signing!</p>
<% end %>

<h1 id="about_us">About Us</h1>
<img src="overlook.png" alt="The Overlook Hotel">


<form action="/entries" method="post">
  <label for="guestbook">Guestbook</label>
  <input type="text" id="guestbook" name="message">

  <input type="submit" value="Sign Guestbook">
</form>





<ul>
  <% @entries.each do |entry| %>
    <li><%= entry.message %></li>

  <% end %>
</ul>

app/views/welcome/index.html.erb
<a href="/about">About Us</a>
<h1 id="welcome">Overlook Hotel</h1>


<%= link_to("Register", new_user_path) %>

app/views/welcome/thanks.html.erb
<h1>Thanks for signing!</h1>